---
theme: "rioxx2"
#resourceDir: this is configured with env variable "$HUGO_RESOURCEDIR"
languageCode: "en-gb"
uglyURLs: false
title: "Rioxx"
copyright: "This website and blog are licensed under a <a rel='license' href='https://creativecommons.org/licenses/by/4.0/'>Creative Commons Attribution 4.0 International License</a>"
enableRobotsTXT: true
metaDataFormat: "yaml"
enableGitInfo: false
disablePathToLower: true
#paginate: 20
#summaryLength: 70
#permalinks:
#  page:
#    post: "/news/:year/:filename/"
menu:
  main:
    - name: Home
      pageRef: /
      weight: 10
    - name: "Metadata Profile"
      pageRef: /profiles
      weight: 30
    - name: News
      pageRef: /post
      weight: 35
    - name: Governance
      pageRef: /governance
      weight: 40
    - name: Feedback
      pageRef: /feedback
      weight: 50
    - name: About
      pageRef: /about
      weight: 90
caches:
  getjson:
    dir: :cacheDir/:project
    maxAge: 5s
  getresource:
    dir: :cacheDir/:project
    maxAge: 5s
  getcsv:
    dir: :cacheDir/:project
    maxAge: 5s
params:
  strapline: "The Research Outputs Metadata Schema"
  googleCustomSearchEngineID: ""
  googleSiteVerification: ""
  googleAnalyticsID: ""
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
#      wrapStandAloneImageWithinParagraph: false
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: pygments
    tabWidth: 4
---